services:
  node:
    command: bash
    image: node:18
    restart: unless-stopped
    stdin_open: true
    tty: true
    user: node
    volumes:
      - ./1_The_Physical/Level_1_Stateless_Guess_Point/1_Arrange_Act_Assert_Backwards/2_1_Password_Validator:/home/node/app
    working_dir: /home/node/app